-- 6. CHAT HISTORY TABLE
create table public.chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  message text not null,
  is_user boolean default true,
  is_error boolean default false,
  type text default 'text', -- 'text', 'time_slots', 'summary', 'clinic_list'
  meta_data jsonb, -- Store JSON data for rich responses
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Secure the chat history table
alter table public.chat_history enable row level security;

create policy "Users can CRUD their own chat history."
  on chat_history for all
  using ( auth.uid() = user_id );
