-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE (Public User Data)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  full_name text,
  ic_number text,
  phone text,
  blood_type text default 'Unknown',
  allergies text default 'None',
  emergency_contact text default 'Not Set',
  medical_condition text default 'None',
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Secure the profiles table
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. MEDICATIONS TABLE
create table public.medications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  dosage text default '1 pill',
  pills_to_take int default 1,
  time timestamp with time zone not null,
  instructions text,
  is_taken boolean default false,
  is_one_time boolean default false,
  is_bg_task_enabled boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.medications enable row level security;

create policy "Users can CRUD their own medications."
  on medications for all
  using ( auth.uid() = user_id );

-- 3. FOOD LOGS TABLE
create table public.food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  calories int not null,
  entry_type text default 'food', -- 'food' or 'drink'
  meta_data jsonb, -- Store specific types like 'water', 'coffee'
  logged_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.food_logs enable row level security;

create policy "Users can CRUD their own food logs."
  on food_logs for all
  using ( auth.uid() = user_id );

-- 4. CHECK-INS TABLE (Safe Entry)
create table public.check_ins (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  location_name text not null,
  address text,
  check_in_time timestamp with time zone default timezone('utc'::text, now())
);

alter table public.check_ins enable row level security;

create policy "Users can insert and view their own check-ins."
  on check_ins for all
  using ( auth.uid() = user_id );

-- 5. GAMIFICATION / USER PROGRESS
create table public.user_progress (
  user_id uuid references auth.users not null primary key,
  level int default 1,
  xp double precision default 0, -- helper for double xp
  points int default 0,
  redeemed_vouchers text[] default '{}',
  daily_quests jsonb default '{}', -- { "checkIn": false, "meds": false, "mood": false, "last_date": "2023-10-27" }
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.user_progress enable row level security;

create policy "Users can view and update their own progress."
  on user_progress for all
  using ( auth.uid() = user_id );

-- HANDLE NEW USER SIGNUP (Trigger)
-- This automatically creates a profile entry when a user signs up via Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, username, ic_number, phone)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'username',
    new.raw_user_meta_data->>'ic_number',
    new.raw_user_meta_data->>'phone'
  );
  
  insert into public.user_progress (user_id)
  values (new.id);
  
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
