-- Create Vaccine Records Table
CREATE TABLE public.vaccine_records (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    vaccine_name text NOT NULL,
    date_administered date NOT NULL,
    location text NOT NULL,
    batch_number text NOT NULL,
    dose_number int NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.vaccine_records ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only see their own records
CREATE POLICY "Users can see own vaccine records" 
ON public.vaccine_records FOR SELECT 
USING (auth.uid() = user_id);

-- Note: We can't easily seed data for *specific* users since user_ids are generated by Supabase Auth.
-- The app logic will need to handle "empty state" gracefully, or we provide a function to "generate fake records" for the current user.

-- Function to Generate Fake Cert for Current User (For Demo Purposes)
CREATE OR REPLACE FUNCTION public.generate_demo_vaccine_record()
RETURNS void AS $$
DECLARE
  curr_user_id uuid;
BEGIN
  curr_user_id := auth.uid();
  
  IF curr_user_id IS NOT NULL THEN
    INSERT INTO public.vaccine_records (user_id, vaccine_name, date_administered, location, batch_number, dose_number)
    VALUES 
    (curr_user_id, 'Pfizer-BioNTech', '2021-05-20', 'PPV World Trade Centre', 'FD1234', 1),
    (curr_user_id, 'Pfizer-BioNTech', '2021-06-10', 'PPV World Trade Centre', 'FD5678', 2),
    (curr_user_id, 'Pfizer (Booster)', '2022-01-15', 'Klinik Kesihatan KL', 'GH9012', 3);
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
