import 'package:flutter/services.dart';
import 'package:my_sejahtera_ng/core/providers/user_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  Future<void> generateAndShareCertificate(UserSession user) async {
    final pdf = pw.Document();

    // Load fonts with fallback
    pw.Font font;
    pw.Font fontBold;
    try {
      print("Loading Google Fonts...");
      font = await PdfGoogleFonts.outfitRegular();
      fontBold = await PdfGoogleFonts.outfitBold();
      print("Google Fonts loaded successfully.");
    } catch (e) {
      print("Error loading Google Fonts: $e. Using standard fonts.");
      font = pw.Font.courier();
      fontBold = pw.Font.courierBold();
    }

    // Load MySejahtera Logo (using a placeholder or asset if available)
    // For now, we'll use text as the logo or a simple shape

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Container(
            padding: const pw.EdgeInsets.all(30),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.amber, width: 4),
              borderRadius: pw.BorderRadius.circular(20),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.SizedBox(height: 20),
                pw.Text("DIGITAL CERTIFICATE", style: pw.TextStyle(font: fontBold, fontSize: 24, letterSpacing: 2)),
                pw.SizedBox(height: 10),
                pw.Text("COVID-19 VACCINATION", style: pw.TextStyle(font: font, fontSize: 16, color: PdfColors.grey700)),
                pw.Divider(thickness: 2, color: PdfColors.amber),
                pw.SizedBox(height: 40),

                // User Info
                pw.Text(user.fullName.toUpperCase(), style: pw.TextStyle(font: fontBold, fontSize: 28)),
                pw.SizedBox(height: 10),
                pw.Text("IC / Passport: ${user.icNumber}", style: pw.TextStyle(font: font, fontSize: 18)),
                pw.SizedBox(height: 40),

                // Status
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 30, vertical: 10),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.green100,
                    borderRadius: pw.BorderRadius.circular(20),
                    border: pw.Border.all(color: PdfColors.green)
                  ),
                  child: pw.Text("FULLY VACCINATED", style: pw.TextStyle(font: fontBold, fontSize: 20, color: PdfColors.green800)),
                ),
                pw.SizedBox(height: 40),

                // QR Code Placeholder (Generating actual QR in PDF is complex, using barcode widget)
                pw.BarcodeWidget(
                  barcode: pw.Barcode.qrCode(),
                  data: "https://mysejahtera.malaysia.gov.my?id=${user.username}",
                  width: 200,
                  height: 200,
                ),
                
                pw.Spacer(),
                pw.Text("Generated by MySejahtera NG", style: pw.TextStyle(font: font, fontSize: 12, color: PdfColors.grey500)),
                pw.Text(DateTime.now().toString(), style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
              ],
            ),
          );
        },
      ),
    );

    // Save and Share (Cross-Platform)
    // This works on Mobile (Share Sheet) and Web (Download)
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'MySejahtera_Certificate.pdf',
    );
  }
}
